[package]
name = "lightmem-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "lightmem"
crate-type = ["cdylib"]
test = false

[dependencies]
lightmem-core = { path = "../lightmem-core" }
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py38"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
