// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(lightmem_ffiFFI)
import lightmem_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_lightmem_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_lightmem_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol LightMemProtocol : AnyObject {
    
    func answer(question: String, needle: Bool?, category: String?, asOf: String?, limit: UInt32?) throws  -> FfiAnswerResult
    
    func dbPath()  -> String
    
    func exportOkf(outputPath: String?) throws  -> String
    
    func forget(id: String, hard: Bool) throws  -> Bool
    
    func importFile(path: String, needle: Bool?) throws  -> UInt64
    
    func list(category: String?, status: String?, asOf: String?, limit: UInt32?) throws  -> [FfiMemoryRecord]
    
    func recall(query: String, category: String?, asOf: String?, limit: UInt32?, minSimilarity: Float?) throws  -> [FfiScoredMemory]
    
    func remember(content: String, category: String?, title: String?, tags: [String], confidence: Float?) throws  -> FfiMemoryRecord
    
    func stats() throws  -> FfiStorageStats
    
}

open class LightMem:
    LightMemProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_lightmem_ffi_fn_clone_lightmem(self.pointer, $0) }
    }
public convenience init(dbPath: String?, globalDb: Bool)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeLightMemFfiError.lift) {
    uniffi_lightmem_ffi_fn_constructor_lightmem_new(
        FfiConverterOptionString.lower(dbPath),
        FfiConverterBool.lower(globalDb),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_lightmem_ffi_fn_free_lightmem(pointer, $0) }
    }

    

    
open func answer(question: String, needle: Bool?, category: String?, asOf: String?, limit: UInt32?)throws  -> FfiAnswerResult {
    return try  FfiConverterTypeFfiAnswerResult.lift(try rustCallWithError(FfiConverterTypeLightMemFfiError.lift) {
    uniffi_lightmem_ffi_fn_method_lightmem_answer(self.uniffiClonePointer(),
        FfiConverterString.lower(question),
        FfiConverterOptionBool.lower(needle),
        FfiConverterOptionString.lower(category),
        FfiConverterOptionString.lower(asOf),
        FfiConverterOptionUInt32.lower(limit),$0
    )
})
}
    
open func dbPath() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_lightmem_ffi_fn_method_lightmem_db_path(self.uniffiClonePointer(),$0
    )
})
}
    
open func exportOkf(outputPath: String?)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeLightMemFfiError.lift) {
    uniffi_lightmem_ffi_fn_method_lightmem_export_okf(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(outputPath),$0
    )
})
}
    
open func forget(id: String, hard: Bool)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeLightMemFfiError.lift) {
    uniffi_lightmem_ffi_fn_method_lightmem_forget(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterBool.lower(hard),$0
    )
})
}
    
open func importFile(path: String, needle: Bool?)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeLightMemFfiError.lift) {
    uniffi_lightmem_ffi_fn_method_lightmem_import_file(self.uniffiClonePointer(),
        FfiConverterString.lower(path),
        FfiConverterOptionBool.lower(needle),$0
    )
})
}
    
open func list(category: String?, status: String?, asOf: String?, limit: UInt32?)throws  -> [FfiMemoryRecord] {
    return try  FfiConverterSequenceTypeFfiMemoryRecord.lift(try rustCallWithError(FfiConverterTypeLightMemFfiError.lift) {
    uniffi_lightmem_ffi_fn_method_lightmem_list(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(category),
        FfiConverterOptionString.lower(status),
        FfiConverterOptionString.lower(asOf),
        FfiConverterOptionUInt32.lower(limit),$0
    )
})
}
    
open func recall(query: String, category: String?, asOf: String?, limit: UInt32?, minSimilarity: Float?)throws  -> [FfiScoredMemory] {
    return try  FfiConverterSequenceTypeFfiScoredMemory.lift(try rustCallWithError(FfiConverterTypeLightMemFfiError.lift) {
    uniffi_lightmem_ffi_fn_method_lightmem_recall(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterOptionString.lower(category),
        FfiConverterOptionString.lower(asOf),
        FfiConverterOptionUInt32.lower(limit),
        FfiConverterOptionFloat.lower(minSimilarity),$0
    )
})
}
    
open func remember(content: String, category: String?, title: String?, tags: [String], confidence: Float?)throws  -> FfiMemoryRecord {
    return try  FfiConverterTypeFfiMemoryRecord.lift(try rustCallWithError(FfiConverterTypeLightMemFfiError.lift) {
    uniffi_lightmem_ffi_fn_method_lightmem_remember(self.uniffiClonePointer(),
        FfiConverterString.lower(content),
        FfiConverterOptionString.lower(category),
        FfiConverterOptionString.lower(title),
        FfiConverterSequenceString.lower(tags),
        FfiConverterOptionFloat.lower(confidence),$0
    )
})
}
    
open func stats()throws  -> FfiStorageStats {
    return try  FfiConverterTypeFfiStorageStats.lift(try rustCallWithError(FfiConverterTypeLightMemFfiError.lift) {
    uniffi_lightmem_ffi_fn_method_lightmem_stats(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightMem: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = LightMem

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> LightMem {
        return LightMem(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: LightMem) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightMem {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: LightMem, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightMem_lift(_ pointer: UnsafeMutableRawPointer) throws -> LightMem {
    return try FfiConverterTypeLightMem.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightMem_lower(_ value: LightMem) -> UnsafeMutableRawPointer {
    return FfiConverterTypeLightMem.lower(value)
}


public struct FfiAnswerResult {
    public var answer: String
    public var selectedMemory: FfiMemoryRecord?
    public var confidence: Float
    public var rerankerUsed: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(answer: String, selectedMemory: FfiMemoryRecord?, confidence: Float, rerankerUsed: String) {
        self.answer = answer
        self.selectedMemory = selectedMemory
        self.confidence = confidence
        self.rerankerUsed = rerankerUsed
    }
}



extension FfiAnswerResult: Equatable, Hashable {
    public static func ==(lhs: FfiAnswerResult, rhs: FfiAnswerResult) -> Bool {
        if lhs.answer != rhs.answer {
            return false
        }
        if lhs.selectedMemory != rhs.selectedMemory {
            return false
        }
        if lhs.confidence != rhs.confidence {
            return false
        }
        if lhs.rerankerUsed != rhs.rerankerUsed {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(answer)
        hasher.combine(selectedMemory)
        hasher.combine(confidence)
        hasher.combine(rerankerUsed)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAnswerResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAnswerResult {
        return
            try FfiAnswerResult(
                answer: FfiConverterString.read(from: &buf), 
                selectedMemory: FfiConverterOptionTypeFfiMemoryRecord.read(from: &buf), 
                confidence: FfiConverterFloat.read(from: &buf), 
                rerankerUsed: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAnswerResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.answer, into: &buf)
        FfiConverterOptionTypeFfiMemoryRecord.write(value.selectedMemory, into: &buf)
        FfiConverterFloat.write(value.confidence, into: &buf)
        FfiConverterString.write(value.rerankerUsed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAnswerResult_lift(_ buf: RustBuffer) throws -> FfiAnswerResult {
    return try FfiConverterTypeFfiAnswerResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAnswerResult_lower(_ value: FfiAnswerResult) -> RustBuffer {
    return FfiConverterTypeFfiAnswerResult.lower(value)
}


public struct FfiCategoryCount {
    public var category: String
    public var count: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(category: String, count: UInt64) {
        self.category = category
        self.count = count
    }
}



extension FfiCategoryCount: Equatable, Hashable {
    public static func ==(lhs: FfiCategoryCount, rhs: FfiCategoryCount) -> Bool {
        if lhs.category != rhs.category {
            return false
        }
        if lhs.count != rhs.count {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(category)
        hasher.combine(count)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiCategoryCount: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiCategoryCount {
        return
            try FfiCategoryCount(
                category: FfiConverterString.read(from: &buf), 
                count: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiCategoryCount, into buf: inout [UInt8]) {
        FfiConverterString.write(value.category, into: &buf)
        FfiConverterUInt64.write(value.count, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCategoryCount_lift(_ buf: RustBuffer) throws -> FfiCategoryCount {
    return try FfiConverterTypeFfiCategoryCount.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiCategoryCount_lower(_ value: FfiCategoryCount) -> RustBuffer {
    return FfiConverterTypeFfiCategoryCount.lower(value)
}


public struct FfiMemoryRecord {
    public var id: String
    public var category: String
    public var title: String
    public var content: String
    public var tags: [String]
    public var confidence: Float
    public var status: String
    public var provenance: String
    public var createdAt: String
    public var updatedAt: String
    public var expiredAt: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, category: String, title: String, content: String, tags: [String], confidence: Float, status: String, provenance: String, createdAt: String, updatedAt: String, expiredAt: String?) {
        self.id = id
        self.category = category
        self.title = title
        self.content = content
        self.tags = tags
        self.confidence = confidence
        self.status = status
        self.provenance = provenance
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.expiredAt = expiredAt
    }
}



extension FfiMemoryRecord: Equatable, Hashable {
    public static func ==(lhs: FfiMemoryRecord, rhs: FfiMemoryRecord) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.category != rhs.category {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        if lhs.tags != rhs.tags {
            return false
        }
        if lhs.confidence != rhs.confidence {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        if lhs.provenance != rhs.provenance {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.updatedAt != rhs.updatedAt {
            return false
        }
        if lhs.expiredAt != rhs.expiredAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(category)
        hasher.combine(title)
        hasher.combine(content)
        hasher.combine(tags)
        hasher.combine(confidence)
        hasher.combine(status)
        hasher.combine(provenance)
        hasher.combine(createdAt)
        hasher.combine(updatedAt)
        hasher.combine(expiredAt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMemoryRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMemoryRecord {
        return
            try FfiMemoryRecord(
                id: FfiConverterString.read(from: &buf), 
                category: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf), 
                confidence: FfiConverterFloat.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                provenance: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf), 
                expiredAt: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMemoryRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.category, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterFloat.write(value.confidence, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterString.write(value.provenance, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
        FfiConverterOptionString.write(value.expiredAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMemoryRecord_lift(_ buf: RustBuffer) throws -> FfiMemoryRecord {
    return try FfiConverterTypeFfiMemoryRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMemoryRecord_lower(_ value: FfiMemoryRecord) -> RustBuffer {
    return FfiConverterTypeFfiMemoryRecord.lower(value)
}


public struct FfiScoredMemory {
    public var memory: FfiMemoryRecord
    public var score: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(memory: FfiMemoryRecord, score: Float) {
        self.memory = memory
        self.score = score
    }
}



extension FfiScoredMemory: Equatable, Hashable {
    public static func ==(lhs: FfiScoredMemory, rhs: FfiScoredMemory) -> Bool {
        if lhs.memory != rhs.memory {
            return false
        }
        if lhs.score != rhs.score {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(memory)
        hasher.combine(score)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiScoredMemory: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiScoredMemory {
        return
            try FfiScoredMemory(
                memory: FfiConverterTypeFfiMemoryRecord.read(from: &buf), 
                score: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: FfiScoredMemory, into buf: inout [UInt8]) {
        FfiConverterTypeFfiMemoryRecord.write(value.memory, into: &buf)
        FfiConverterFloat.write(value.score, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScoredMemory_lift(_ buf: RustBuffer) throws -> FfiScoredMemory {
    return try FfiConverterTypeFfiScoredMemory.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiScoredMemory_lower(_ value: FfiScoredMemory) -> RustBuffer {
    return FfiConverterTypeFfiScoredMemory.lower(value)
}


public struct FfiStorageStats {
    public var totalMemories: UInt64
    public var activeMemories: UInt64
    public var expiredMemories: UInt64
    public var totalVectors: UInt64
    public var byCategory: [FfiCategoryCount]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(totalMemories: UInt64, activeMemories: UInt64, expiredMemories: UInt64, totalVectors: UInt64, byCategory: [FfiCategoryCount]) {
        self.totalMemories = totalMemories
        self.activeMemories = activeMemories
        self.expiredMemories = expiredMemories
        self.totalVectors = totalVectors
        self.byCategory = byCategory
    }
}



extension FfiStorageStats: Equatable, Hashable {
    public static func ==(lhs: FfiStorageStats, rhs: FfiStorageStats) -> Bool {
        if lhs.totalMemories != rhs.totalMemories {
            return false
        }
        if lhs.activeMemories != rhs.activeMemories {
            return false
        }
        if lhs.expiredMemories != rhs.expiredMemories {
            return false
        }
        if lhs.totalVectors != rhs.totalVectors {
            return false
        }
        if lhs.byCategory != rhs.byCategory {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(totalMemories)
        hasher.combine(activeMemories)
        hasher.combine(expiredMemories)
        hasher.combine(totalVectors)
        hasher.combine(byCategory)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiStorageStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiStorageStats {
        return
            try FfiStorageStats(
                totalMemories: FfiConverterUInt64.read(from: &buf), 
                activeMemories: FfiConverterUInt64.read(from: &buf), 
                expiredMemories: FfiConverterUInt64.read(from: &buf), 
                totalVectors: FfiConverterUInt64.read(from: &buf), 
                byCategory: FfiConverterSequenceTypeFfiCategoryCount.read(from: &buf)
        )
    }

    public static func write(_ value: FfiStorageStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.totalMemories, into: &buf)
        FfiConverterUInt64.write(value.activeMemories, into: &buf)
        FfiConverterUInt64.write(value.expiredMemories, into: &buf)
        FfiConverterUInt64.write(value.totalVectors, into: &buf)
        FfiConverterSequenceTypeFfiCategoryCount.write(value.byCategory, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStorageStats_lift(_ buf: RustBuffer) throws -> FfiStorageStats {
    return try FfiConverterTypeFfiStorageStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStorageStats_lower(_ value: FfiStorageStats) -> RustBuffer {
    return FfiConverterTypeFfiStorageStats.lower(value)
}


public enum LightMemFfiError {

    
    
    case StorageError(msg: String
    )
    case InvalidInput(msg: String
    )
    case SerializationError(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightMemFfiError: FfiConverterRustBuffer {
    typealias SwiftType = LightMemFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightMemFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .StorageError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidInput(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .SerializationError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LightMemFfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .StorageError(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidInput(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .SerializationError(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension LightMemFfiError: Equatable, Hashable {}

extension LightMemFfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionFloat: FfiConverterRustBuffer {
    typealias SwiftType = Float?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterFloat.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterFloat.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiMemoryRecord: FfiConverterRustBuffer {
    typealias SwiftType = FfiMemoryRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiMemoryRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiMemoryRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiCategoryCount: FfiConverterRustBuffer {
    typealias SwiftType = [FfiCategoryCount]

    public static func write(_ value: [FfiCategoryCount], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiCategoryCount.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiCategoryCount] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiCategoryCount]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiCategoryCount.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiMemoryRecord: FfiConverterRustBuffer {
    typealias SwiftType = [FfiMemoryRecord]

    public static func write(_ value: [FfiMemoryRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiMemoryRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiMemoryRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiMemoryRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiMemoryRecord.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiScoredMemory: FfiConverterRustBuffer {
    typealias SwiftType = [FfiScoredMemory]

    public static func write(_ value: [FfiScoredMemory], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiScoredMemory.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiScoredMemory] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiScoredMemory]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiScoredMemory.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_lightmem_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_lightmem_ffi_checksum_method_lightmem_answer() != 46825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lightmem_ffi_checksum_method_lightmem_db_path() != 21462) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lightmem_ffi_checksum_method_lightmem_export_okf() != 43945) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lightmem_ffi_checksum_method_lightmem_forget() != 35660) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lightmem_ffi_checksum_method_lightmem_import_file() != 6957) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lightmem_ffi_checksum_method_lightmem_list() != 48006) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lightmem_ffi_checksum_method_lightmem_recall() != 13621) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lightmem_ffi_checksum_method_lightmem_remember() != 40970) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lightmem_ffi_checksum_method_lightmem_stats() != 63989) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lightmem_ffi_checksum_constructor_lightmem_new() != 65282) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all